version: '3.5'

services:
  nest:
    container_name: nest_container
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: postgres_container
    build: ./docker/postgres
    env_file:
      - .env
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER:-postgres}",
          "-d",
          "${POSTGRES_DB:-postgres_db}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  pg_admin:
    container_name: pgadmin_container
    build: ./docker/pgadmin
    env_file:
      - .env
    volumes:
      - pgadmin:${PGADATA}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
